POST https://node-do-zero-3msk.onrender.com/videos
Content-Type: application/json

{
  "title": "video node",
  "description": "Esse é o primeiro video.",
  "duration": 180
}

###

# GET https://node-do-zero-3msk.onrender.com/videos?search=node
GET https://node-do-zero-3msk.onrender.com/videos

###

PUT https://node-do-zero-3msk.onrender.com/videos/e97b4148-3817-44c8-a167-48de4c73fb34
Content-Type: application/json

{
  "title": "Video 001 node",
  "description": "Esse é o primeiro video.",
  "duration": 180
}

###

DELETE https://node-do-zero-3msk.onrender.com/videos/aad69d07-1e5a-4ba3-99c7-b15acd94c3be